apiVersion: v1
kind: Service
metadata:
  labels:
    app: microbot
  name: microbotpv
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: microbot
  sessionAffinity: None
  type: LoadBalancer
